# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: "PAO: Rename Artifacts by Part Number"
author: "HashiCorp"
description: "Rename artifacts by CSV mapping part numbers from eBOMs in a provided meta directory for PAO releases"

branding:
  color: "blue"
  icon: "package"

inputs:
  pao_meta_dir:
    description: 'The path to the PAO meta directory'
    required: true
    type: string
  input_dir:
    description: 'The input directory containing the artifacts to rename'
    required: true
    type: string
  output_dir:
    description: 'The output directory containing the renamed artifacts'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Install csvkit
      shell: bash
      run: "${GITHUB_ACTION_PATH}/../scripts/install-csvkit"
    - name: Rename files by part number
      shell: bash
      env:
        PAO_META_DIR: ${{ inputs.pao_meta_dir }}
        INPUT_DIR: ${{ inputs.input_dir }}
        OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |  
        # Name the files in the input directory by part-number in the output directory
        "${GITHUB_ACTION_PATH}"/../scripts/rename-by-part-number.sh \
          "$PAO_META_DIR" "$INPUT_DIR" "$OUTPUT_DIR" || {
            err "Failed to rename files by part number."
            exit 1
          }
